[phases.setup]
nixPkgs=[
    "python310",
    "ffmpeg",
    "opus",
    "python310Packages.pip",
    "gcc",
    "libffi",
    "libsodium"
]

[phases.install]
cmds=[
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd="python3 discordBot.py"