[phases.setup]
aptPkgs = ['python3.11', 'python3-pip', 'ffmpeg', 'libopus0', 'libopus-dev', 'opus-tools']

[phases.build]
cmds = [
    'python -m pip install --upgrade pip',
    'pip install -r requirements.txt'
]