[phases.setup]
nixPkgs = ['python311', 'ffmpeg', 'gcc', 'python311Packages.pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['pip install --no-cache-dir -r requirements.txt']